# Generated by Django 3.1.1 on 2020-10-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0002_directorate_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='doctor',
            field=models.ForeignKey(default=0.0005076142131979696, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
            preserve_default=False,
        ),
    ]
