# Generated by Django 3.1.1 on 2020-10-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0002_auto_20201019_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askdoctor',
            name='created',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=868167, null=True, unique=True),
        ),
    ]
