# Generated by Django 3.1.1 on 2020-10-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0003_auto_20201019_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='askdoctor',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=952310, null=True, unique=True),
        ),
    ]
