# Generated by Django 3.1.2 on 2020-10-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0004_auto_20201019_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=451285, null=True, unique=True),
        ),
    ]
