# Generated by Django 3.1.1 on 2020-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0004_auto_20201007_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
