# Generated by Django 3.1.1 on 2020-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0005_auto_20201007_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
