# Generated by Django 3.1.1 on 2020-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0006_auto_20201007_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('TK', 'Trưởng Khoa'), ('PK', 'Phó Khoa'), ('DDT', 'Điều dưỡng trưởng')], max_length=200),
        ),
    ]
