# Generated by Django 3.1.2 on 2020-10-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0006_auto_20201019_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.university'),
        ),
        migrations.AlterField(
            model_name='education',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
        ),
        migrations.AlterField(
            model_name='education',
            name='main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=318700, null=True, unique=True),
        ),
    ]
