# Generated by Django 3.1.1 on 2020-10-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0007_auto_20201007_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
    ]
