# Generated by Django 3.1.2 on 2020-10-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0007_auto_20201019_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='askdoctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/asks/'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=803179, null=True, unique=True),
        ),
    ]
