# Generated by Django 3.1.2 on 2020-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0009_auto_20201019_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='aswer',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=533308, null=True, unique=True),
        ),
    ]
