# Generated by Django 3.1.1 on 2020-10-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0009_auto_20201007_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='thumbnail',
            new_name='avatar',
        ),
    ]
