# Generated by Django 3.1.1 on 2020-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0010_auto_20201007_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='finddoctor/static/finddoctor/avatars'),
        ),
    ]
