# Generated by Django 3.1.1 on 2020-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0011_auto_20201008_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='show_in_home',
            field=models.BooleanField(default=False, help_text='Có xuất hiện ở mục bác sĩ nổi bật tại trang chủ'),
        ),
    ]
