# Generated by Django 3.1.1 on 2020-10-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0011_auto_20201019_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=700696, null=True, unique=True),
        ),
    ]
