# Generated by Django 3.1.1 on 2020-10-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0012_auto_20201020_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorate',
            name='role',
            field=models.CharField(choices=[('Giám Đốc', 'Giám Đốc'), ('Phó Giám Đốc', 'Phó Giám Đốc')], max_length=200),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=506740, null=True, unique=True),
        ),
    ]
