# Generated by Django 3.1.1 on 2020-10-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0012_auto_20201008_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='finddoctor/static/imgs/avatars'),
        ),
    ]
