# Generated by Django 3.1.1 on 2020-10-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0016_auto_20201008_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='show_in_home',
            new_name='showinhome',
        ),
    ]
