# Generated by Django 3.1.1 on 2020-10-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0017_auto_20201009_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
