# Generated by Django 3.1.2 on 2020-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0017_auto_20201020_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askdoctor',
            name='created',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=385232, null=True, unique=True),
        ),
    ]
