# Generated by Django 3.1.1 on 2020-10-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0018_education_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='highlight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
