# Generated by Django 3.1.2 on 2020-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0018_auto_20201020_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askdoctor',
            name='isanswer',
        ),
        migrations.RemoveField(
            model_name='askdoctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='askdoctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=662086, null=True, unique=True),
        ),
    ]
