# Generated by Django 3.1.1 on 2020-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0019_doctor_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/avatars/'),
        ),
    ]
