# Generated by Django 3.1.1 on 2020-10-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0020_department_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='showinhome',
            field=models.BooleanField(default=False, help_text='Có xuất hiện ở mục nổi bật tại trang chủ'),
        ),
    ]
