# Generated by Django 3.1.2 on 2020-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0021_auto_20201020_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askdoctor',
            name='isanswer',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=137727, null=True, unique=True),
        ),
    ]
