# Generated by Django 3.1.2 on 2020-10-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='finddoctor/static/finddoctor/imgs/noavatar.png', null=True, upload_to='imgs/avatars/'),
        ),
    ]
