# Generated by Django 3.1.2 on 2020-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0023_auto_20201020_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='askdoctor',
            name='isanswer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=200818, null=True, unique=True),
        ),
    ]
