# Generated by Django 3.1.1 on 2020-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0027_auto_20201014_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
