# Generated by Django 3.1.2 on 2020-10-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finddoctor', '0027_auto_20201021_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=629197, null=True, unique=True),
        ),
    ]
