# Generated by Django 3.1.2 on 2020-10-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0028_auto_20201021_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=814726, null=True, unique=True),
        ),
    ]
