# Generated by Django 3.1.1 on 2020-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0029_auto_20201021_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=297335, null=True, unique=True),
        ),
    ]
