# Generated by Django 3.1.1 on 2020-10-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0029_auto_20201014_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapartment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookapartment',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
