# Generated by Django 3.1.1 on 2020-10-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0030_auto_20201014_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookapartment',
            old_name='order_name',
            new_name='ordername',
        ),
        migrations.RenameField(
            model_name='bookapartment',
            old_name='order_phone',
            new_name='orderphone',
        ),
    ]
