# Generated by Django 3.1.1 on 2020-10-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0031_auto_20201014_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapartment',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
