# Generated by Django 3.1.1 on 2020-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0032_auto_20201014_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapartment',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
