# Generated by Django 3.1.1 on 2020-10-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0033_auto_20201014_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapartment',
            name='dotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
        ),
    ]
