# Generated by Django 3.1.2 on 2020-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0036_auto_20201014_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=717637, null=True, unique=True),
        ),
    ]
