# Generated by Django 3.1.2 on 2020-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0037_auto_20201014_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookapartment',
            old_name='dotor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='reviewdoctor',
            old_name='description',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='apartments',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=237060, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookapartment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=684605, null=True),
        ),
    ]
