# Generated by Django 3.1.2 on 2020-10-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0038_auto_20201014_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdoctor',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartments',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=408128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookapartment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=497850, null=True),
        ),
    ]
