# Generated by Django 3.1.2 on 2020-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0040_auto_20201014_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapartment',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=391689, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookapartment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=761919, null=True),
        ),
        migrations.AlterField(
            model_name='reviewdoctor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
