# Generated by Django 3.1.2 on 2020-10-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0041_auto_20201014_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookapartment',
            name='verify',
        ),
        migrations.AddField(
            model_name='reviewdoctor',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=791953, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookapartment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=566499, null=True),
        ),
    ]
