# Generated by Django 3.1.1 on 2020-10-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0043_auto_20201015_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=928870, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookapartment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=502806, null=True),
        ),
    ]
