# Generated by Django 3.1.1 on 2020-10-16 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finddoctor', '0056_auto_20201016_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertify_code', models.IntegerField(blank=True, default=911151, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookapartment',
            name='vertify_code',
        ),
        migrations.DeleteModel(
            name='Apartments',
        ),
        migrations.AddField(
            model_name='appointment',
            name='bookapartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finddoctor.bookapartment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
