# Generated by Django 3.1.1 on 2020-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0058_auto_20201016_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=847765, null=True, unique=True),
        ),
    ]
