# Generated by Django 3.1.1 on 2020-10-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0060_auto_20201016_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=940016, null=True, unique=True),
        ),
    ]
