# Generated by Django 3.1.1 on 2020-10-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0062_auto_20201016_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=440056, null=True, unique=True),
        ),
    ]
