# Generated by Django 3.1.2 on 2020-10-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0064_auto_20201017_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vertify_code',
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertify_code', models.IntegerField(blank=True, default=900772, null=True, unique=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finddoctor.appointment')),
            ],
        ),
    ]
