# Generated by Django 3.1.2 on 2020-10-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0065_auto_20201017_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=826647, null=True, unique=True),
        ),
    ]
