# Generated by Django 3.1.2 on 2020-10-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0066_auto_20201017_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
        ),
        migrations.AlterField(
            model_name='bookapartment',
            name='status',
            field=models.CharField(blank=True, choices=[('ĐC', 'Đang Chờ Khám'), ('ĐX', 'Đã Khám Xong')], default='Đang Chờ Khám', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=228748, null=True, unique=True),
        ),
    ]
