# Generated by Django 3.1.2 on 2020-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0067_auto_20201017_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=808047, null=True, unique=True),
        ),
    ]
