# Generated by Django 3.1.2 on 2020-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0068_auto_20201017_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapartment',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=867584, null=True, unique=True),
        ),
    ]
