# Generated by Django 3.1.2 on 2020-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0069_auto_20201017_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookapartment',
            old_name='status',
            new_name='isdone',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=373478, null=True, unique=True),
        ),
    ]
