# Generated by Django 3.1.2 on 2020-10-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0070_auto_20201017_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapartment',
            name='isdone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=505523, null=True, unique=True),
        ),
    ]
