# Generated by Django 3.1.2 on 2020-10-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0072_auto_20201017_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('Bác Sĩ', 'Bác Sĩ'), ('Bác Sĩ', 'Bác Sĩ'), ('Phó Khoa', 'Phó Khoa'), ('Điều dưỡng trưởng', 'Điều dưỡng trưởng')], max_length=200),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=873252, null=True, unique=True),
        ),
    ]
