# Generated by Django 3.1.2 on 2020-10-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0074_auto_20201018_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapartment',
            name='isdone',
            field=models.CharField(blank=True, choices=[('Đang chờ khám', 'Đang chờ khám'), ('Đã khám xong', 'Đã khám xong'), ('Đã huỷ', 'Đã huỷ')], default='Đang chờ khám', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=235863, null=True, unique=True),
        ),
    ]
