# Generated by Django 3.1.2 on 2020-10-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0075_auto_20201018_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.education'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=997400, null=True, unique=True),
        ),
    ]
