# Generated by Django 3.1.2 on 2020-10-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0076_auto_20201018_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.AddField(
            model_name='education',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=610977, null=True, unique=True),
        ),
    ]
