# Generated by Django 3.1.1 on 2020-10-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0077_auto_20201018_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=459701, null=True, unique=True),
        ),
    ]
