# Generated by Django 3.1.1 on 2020-10-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0080_auto_20201019_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('Trưởng khoa', 'Trưởng khoa'), ('Bác Sĩ', 'Bác Sĩ'), ('Phó Khoa', 'Phó Khoa'), ('Điều dưỡng trưởng', 'Điều dưỡng trưởng')], max_length=200),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=343394, null=True, unique=True),
        ),
    ]
