# Generated by Django 3.1.1 on 2020-10-19 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finddoctor', '0081_auto_20201019_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=718052, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AskDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aswer', models.TextField(blank=True, max_length=1000, null=True)),
                ('ask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.askdoctor')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finddoctor.doctor')),
            ],
        ),
    ]
