# Generated by Django 3.1.1 on 2020-10-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0085_auto_20201019_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='vertify_code',
            field=models.IntegerField(blank=True, default=779647, null=True, unique=True),
        ),
    ]
